coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 0.1%
      range:
        30..100

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "!*-dev"
